/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LikerRouteImport } from './routes/liker'
import { Route as IndexRouteImport } from './routes/index'

const LikerRoute = LikerRouteImport.update({
  id: '/liker',
  path: '/liker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liker': typeof LikerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liker': typeof LikerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liker': typeof LikerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liker'
  id: '__root__' | '/' | '/liker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LikerRoute: typeof LikerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/liker': {
      id: '/liker'
      path: '/liker'
      fullPath: '/liker'
      preLoaderRoute: typeof LikerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LikerRoute: LikerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
